# Site settings
title: 大晴天
description: ""
keywords: Modern, Blogging, Fun
author: 晴天
baseurl: "jiqingtian.com" # the subpath of your site, e.g. /blog/
url: "jiqingtian.com" # the base hostname & protocol for your site

theme: jekyll-theme-architect
